### PR TITLE
Fix -PE  bugs

### LINKED ISSUE #147: [PE-D] Formatting error in User Guide (timetable)
There is a small formatting error in the User Guide below the sorting contacts feature.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: goatygoatygoat/ped#16

### LINKED ISSUE #148: [PE-D] UG: Target user unclear
The target user is unclear from the introduction of the UG.

Suggestion: it would be great if the target user of the application was specified more clearly, e.g. "this app was meant for people who are desperate for finding friends".

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: arsatis/ped#1

### LINKED ISSUE #149: [PE-D] GUI: Header name
The header of the GUI is different from the name of the application.

The name of the team's product is MeetBuddy, but the name of the app is "Address App".

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: arsatis/ped#2

### LINKED ISSUE #150: [PE-D] GUI: Timetable panel unreadable on small window size
The timetable panel is unreadable when GUI gets too small. See image attached.

How to reproduce: shrink the window horizontally until its minimum possible width.
Suggestion: maybe the team could consider hiding the person panel for smaller window sizes?

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: arsatis/ped#3

### LINKED ISSUE #151: [PE-D] GUI: Laggy scrollbar
There might be a Thread.sleep() somewhere in the code that causes the scrollbar to lag when the user tries to scroll through the list of persons. It might have been added to prevent the app from updating instantaneously, but gives rise to poor UX.

How to replicate: just click on the scrollbar of the persons list, and shift it upwards/downwards for a few times. Lags will be evident.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: arsatis/ped#4

### LINKED ISSUE #152: [PE-D] GUI: Typo in app
There is a typo in the word "TimeTable" - timetable is a single word, not two separate words. The letter "t" in "table" should not be capitalized in the GUI. See image attached.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: arsatis/ped#5

### LINKED ISSUE #159: [PE-D] UG: Hard-to-understand command
The explanation for the command/feature in the attached image is weird and hard to comprehend. I'm still not too sure what is this or why is this here even after re-reading it for a few times. See image attached.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: arsatis/ped#12

### LINKED ISSUE #167: [PE-D] GUI: setTimetable behaviour differs from User Guide
The command "setTimetable" without a parameter updates the app to today's date. This behavior was not specified in the User Guide.

How to replicate: key in the command "setTimetable" without any other parameters/fields.
Suggestion: the team may want to consider updating the UG to include this behaviour.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: arsatis/ped#20

### LINKED ISSUE #168: [PE-D] GUI: setTimetable behaviour differs from normal expectations
Keying in the command "setTimetable 9999-11-31" sets the timetable to 30 November 9999, instead of throwing an error that the date is invalid.

How to replicate: key in the command "setTimetable 9999-11-31". The result will not be what was intended by the user.
Suggestion: the team could make the app throw an error instead when such an invalid date is keyed in.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: arsatis/ped#21

### LINKED ISSUE #171: [PE-D] GUI: addm behaviour differs from normal expectations
Keying the command "addm n/CS2103 Lecture st/2020-02-31 12:00 ed/2020-03-01 14:00 desc/Week 7 pr/5 g/lectures g/SoC p/1 p/10" sets the meeting to begin on 29 February 2020, instead of throwing an error stating that 31 February doesn't exist.

How to replicate: key in the command "addm n/CS2103 Lecture st/2020-02-31 12:00 ed/2020-03-01 14:00 desc/Week 7 pr/5 g/lectures g/SoC p/1 p/10". No invalid date error is thrown.
Suggestion: the team could look into throwing an invalid date error, instead of setting the date to the nearest possible date.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: arsatis/ped#24

### PR DESCRIPTION
**Pull request by Maurice2n97**
Fix bugs spotted during PE

Reduce laggy scroll bar by caching images

Fix UG formatting errors

### CODE REVIEW

File: src/main/java/seedu/address/model/person/Person.java [hunk 1]
```diff
@@ -2,11 +2,10 @@
 
 import static seedu.address.commons.util.CollectionUtil.requireAllNonNull;
 
-import java.util.Collections;
-import java.util.HashSet;
-import java.util.Objects;
-import java.util.Set;
+import java.util.*;
```
Comment (totoyoyo) [inline src/main/java/seedu/address/model/person/Person.java]: Ok I guess this is fine since its java.util.*

File: src/main/java/seedu/address/model/person/ProfilePicture.java [hunk 2]
```diff
@@ -0,0 +1,18 @@
+package seedu.address.model.person;
+
+
+import javafx.scene.image.Image;
+
+import static java.util.Objects.requireNonNull;
```
Comment (totoyoyo) [inline src/main/java/seedu/address/model/person/ProfilePicture.java:6]: We deal with the spacing later

**Review by totoyoyo — COMMENTED** [review]
Alright just tell us when you're ready to merge.

File: src/main/java/seedu/address/model/person/Person.java (hunk 1 above)
Comment (Maurice2n97) [reply src/main/java/seedu/address/model/person/Person.java]: fix towards the end.
